title: Hi! I'm Cole Bontrager
description: A game developer based in Bloomington, IN currently pursuing a Bachelor's in CS at Indiana University
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
