title: Hi! I'm Cole Bontrager
description: A gameplay programmer who is passionate about working with designers to bring their ideas to life
show_downloads: false
google_analytics:
theme: jekyll-theme-slate


